server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl
    driver-class-name: org.mariadb.jdbc.Driver
    username: beomchu
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
    defer-datasource-initialization: true